import { bookingRows, serviceItems, summaryCards, tableStatus, upcomingTimeline, waiterRequests } from "@/data/mock-data";

export function getFallbackDashboardSnapshot() {
  return {
    bookingList: bookingRows.map((booking, index) => ({
      id: index + 1,
      code: booking.id,
      customerName: booking.guest,
      customerPhone: booking.phone,
      bookingDate: booking.date,
      bookingTime: booking.time,
      guestCount: booking.guests,
      zoneId: null,
      tableId: null,
      status: booking.status === "pending" ? "pending" : booking.status === "seated" ? "seated" : "confirmed",
      note: booking.note,
      createdAt: new Date(),
      updatedAt: new Date(),
      zoneName: booking.zone,
      tableCode: booking.table,
    })),
    waiterList: waiterRequests.map((request, index) => ({
      id: index + 1,
      code: request.id,
      tableId: null,
      zoneId: null,
      need: request.need,
      note: request.note,
      status: request.status,
      createdAt: new Date(),
      updatedAt: new Date(),
      zoneName: request.zone,
      tableCode: request.table,
    })),
    tableList: tableStatus.map((table, index) => ({
      id: index + 1,
      code: table.id,
      zoneId: null,
      seats: table.seats,
      status: table.status,
      createdAt: new Date(),
      zoneName: table.zone,
    })),
    stats: {
      bookingsToday: Number(summaryCards[0]?.value ?? 0),
      waiterOpen: 4,
      occupiedTables: 14,
    },
    services: serviceItems.map((item, index) => ({
      id: index + 1,
      name: item.name,
      slug: item.id.toLowerCase(),
      category: item.category,
      description: null,
      priceLabel: item.price,
      imagePath: item.image,
      visible: item.visible,
      sortOrder: index + 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    })),
    timeline: upcomingTimeline,
  };
}
